version: '3.8'
services:
  client:
    image: node:16-slim
    ports:
      - "3000:3000"
    volumes:
      - ./client:/opt
      - client_node_modules:/opt/node_modules
    working_dir: /opt
    environment:
      VITE_API_URL: "http://localhost:4000"
    command:
      - /bin/sh
      - -c
      - npm install && npm run dev -- --host '0.0.0.0'
  server:
    image: node:16
    ports:
      - "4000:4000"
    volumes:
      - ./server:/opt
      - server_node_modules:/opt/node_modules
    links:
      - turn-server
    working_dir: /opt
    environment:
      PORT: '4000'
      TURN_SECRET: secret
      TURN_HOSTNAME: localhost
    command:
      - /bin/sh
      - -c
      - npm install && npm run start:dev

  turn-server:
    image: coturn/coturn
    container_name: turn-server
    environment:
      TURN_SECRET: secret
    command:
      - --use-auth-secret
      - --static-auth-secret=${TURN_SECRET}
      - --realm=coturn.realm.org
      - --no-tls
    network_mode: host
volumes:
  client_node_modules:
  server_node_modules:
